// <auto-generated />
using IncubationWeb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IncubationWeb.Data.Migrations
{
    [DbContext(typeof(IncubDbContext))]
    [Migration("20200120153256_Initial")]
    partial class Initial
    {
        /// <summary>
        /// Implemented to builds the <see cref="Migration.TargetModel" />.
        /// </summary>
        /// <param name="modelBuilder">The <see cref="ModelBuilder" /> to use to build the model.</param>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("IncubationWeb.CurrentConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepeatGetInformation")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Config");
                });
#pragma warning restore 612, 618
        }
    }
}
